export enum RouteName {
  Home = '/',
  Intro = '/intro',
  Login = '/login',
  Signup = '/signup',
  Question = '/question',
  Account = '/account',
  Trainings = '/trainings',
  TrainingCard = '/trainings/:id',
  NotFound = '/not-found',
  Users = '/users',
  UserCard = '/users/:id',
  Friends = '/friends',
  Purchases = '/purchases',
  Orders = '/orders',
  MyTrainings = '/my-trainings',
  AddTraining = '/raining/add',
}
