export enum RouteName {
  Home = '/',
  Intro = '/intro',
  Login = '/login',
  Signup = '/signup',
  QuestionUser = '/question-user',
  QuestionCoach = '/question-coach',
  Account = '/account',
  Trainings = '/trainings',
  TrainingCard = '/trainings/:id',
  NotFound = '/not-found',
  Users = '/users',
  UserCard = '/users/:id',
  Friends = '/friends',
  Purchases = '/purchases',
  Orders = '/orders',
  MyTrainings = '/my-trainings',
  NewTraining = '/raining/new',
}
