import { Gender, ITraining, ITrainingCollection, TrainingDuration, TrainingLevel, TrainingType } from '@fit-friends/shared';
import { fakeCoach } from './fake-user';

const forYouTrainings: ITraining[] = [
  {
    id: '1',
    title: 'cresfit',
    bgImage: '/assets/img/content/thumbnails/preview-01.jpg',
    level: TrainingLevel.Professional,
    type: TrainingType.Crossfit,
    duration: TrainingDuration.Normal,
    price: 1600,
    calories: 1200,
    description: 'description',
    gender: Gender.AnyGender,
    video: 'video.mp4',
    rating: 4,
    coach: fakeCoach,
    isSpecial: false,
    ordersCount: 2,
    ordersSumm: 3200,
    createdAt: '2023-11-05T19:43:17.915Z',
  },
  {
    id: '2',
    title: 'power',
    bgImage: '/assets/img/content/thumbnails/preview-02.jpg',
    level: TrainingLevel.Professional,
    type: TrainingType.Crossfit,
    duration: TrainingDuration.Normal,
    price: 1600,
    calories: 1200,
    description: 'description',
    gender: Gender.AnyGender,
    video: 'video.mp4',
    rating: 4,
    coach: fakeCoach,
    isSpecial: false,
    ordersCount: 2,
    ordersSumm: 3200,
    createdAt: '2023-11-05T19:43:17.915Z',
  },
  {
    id: '3',
    title: 'boxing',
    bgImage: '/assets/img/content/thumbnails/preview-03.jpg',
    level: TrainingLevel.Professional,
    type: TrainingType.Crossfit,
    duration: TrainingDuration.Normal,
    price: 1600,
    calories: 1200,
    description: 'description',
    gender: Gender.AnyGender,
    video: 'video.mp4',
    rating: 4,
    coach: fakeCoach,
    isSpecial: false,
    ordersCount: 2,
    ordersSumm: 3200,
    createdAt: '2023-11-05T19:43:17.915Z',
  },
  {
    id: '4',
    title: 'yoga',
    bgImage: '/assets/img/content/thumbnails/preview-01.jpg',
    level: TrainingLevel.Professional,
    type: TrainingType.Crossfit,
    duration: TrainingDuration.Normal,
    price: 1600,
    calories: 1200,
    description: 'description',
    gender: Gender.AnyGender,
    video: 'video.mp4',
    rating: 4,
    coach: fakeCoach,
    isSpecial: false,
    ordersCount: 2,
    ordersSumm: 3200,
    createdAt: '2023-11-05T19:43:17.915Z',
  },
];

export const fakeForYouTrainings: ITrainingCollection = {
  data: forYouTrainings,
  page: 1,
  total: forYouTrainings.length,
};
