import { Gender, ITraining, ITrainingCollection, TrainingDuration, TrainingLevel, TrainingType } from '@fit-friends/shared';
import { fakeCoach } from './fake-user';
import { faker } from '@faker-js/faker';

const trainingImages = [
  '/training-01.jpg',
  '/training-02.jpg',
  '/training-03.jpg',
  '/training-04.jpg',
  '/training-05.jpg',
  '/training-06.jpg',
  '/training-07.jpg',
  '/training-08.jpg',
  '/training-09.jpg',
  '/training-10.jpg',
  '/training-11.jpg',
  '/training-12.jpg',
];

const forYouTrainings: ITraining[] = [
  {
    id: '1',
    title: 'cresfit',
    bgImage: '/assets/img/content/thumbnails/preview-01.jpg',
    level: TrainingLevel.Professional,
    type: TrainingType.Crossfit,
    duration: TrainingDuration.Normal,
    price: 1600,
    calories: 1200,
    description: 'description',
    gender: Gender.AnyGender,
    video: 'video.mp4',
    rating: 4,
    coach: fakeCoach,
    isSpecial: false,
    ordersCount: 2,
    ordersSumm: 3200,
    createdAt: '2023-11-05T19:43:17.915Z',
  },
  {
    id: '2',
    title: 'power',
    bgImage: '/assets/img/content/thumbnails/preview-02.jpg',
    level: TrainingLevel.Professional,
    type: TrainingType.Crossfit,
    duration: TrainingDuration.Normal,
    price: 1600,
    calories: 1200,
    description: 'description',
    gender: Gender.AnyGender,
    video: 'video.mp4',
    rating: 4,
    coach: fakeCoach,
    isSpecial: false,
    ordersCount: 2,
    ordersSumm: 3200,
    createdAt: '2023-11-05T19:43:17.915Z',
  },
  {
    id: '3',
    title: 'boxing',
    bgImage: '/assets/img/content/thumbnails/preview-03.jpg',
    level: TrainingLevel.Professional,
    type: TrainingType.Crossfit,
    duration: TrainingDuration.Normal,
    price: 1600,
    calories: 1200,
    description: 'description',
    gender: Gender.AnyGender,
    video: 'video.mp4',
    rating: 4,
    coach: fakeCoach,
    isSpecial: false,
    ordersCount: 2,
    ordersSumm: 3200,
    createdAt: '2023-11-05T19:43:17.915Z',
  },
  {
    id: '4',
    title: 'yoga',
    bgImage: '/assets/img/content/thumbnails/preview-01.jpg',
    level: TrainingLevel.Professional,
    type: TrainingType.Crossfit,
    duration: TrainingDuration.Normal,
    price: 1600,
    calories: 1200,
    description: 'description',
    gender: Gender.AnyGender,
    video: 'video.mp4',
    rating: 4,
    coach: fakeCoach,
    isSpecial: false,
    ordersCount: 2,
    ordersSumm: 3200,
    createdAt: '2023-11-05T19:43:17.915Z',
  },
];

export const fakeSpecial: ITraining[] = [
  {
    id: '1',
    title: 'Fitball',
    bgImage: '/assets/img/content/promo-1.png',
    level: TrainingLevel.Professional,
    type: TrainingType.Crossfit,
    duration: TrainingDuration.Normal,
    price: 1600,
    calories: 1200,
    description: 'Горячие предложения на тренировки на фитболе',
    gender: Gender.AnyGender,
    video: 'video.mp4',
    rating: 5,
    coach: fakeCoach,
    isSpecial: false,
    createdAt: '2023-11-05T19:43:17.915Z',
  },
  {
    id: '2',
    title: 'Fleksbend',
    bgImage: '/assets/img/content/promo-2.png',
    level: TrainingLevel.Professional,
    type: TrainingType.Crossfit,
    duration: TrainingDuration.Normal,
    price: 2400,
    calories: 1200,
    description: 'Горячие предложения наТренировки с резинкой для фитнеса',
    gender: Gender.AnyGender,
    video: 'video.mp4',
    rating: 4,
    coach: fakeCoach,
    isSpecial: false,
    createdAt: '2023-11-05T19:43:17.915Z',
  },
  {
    id: '3',
    title: 'Full Body Stretch',
    bgImage: '/assets/img/content/promo-3.png',
    level: TrainingLevel.Professional,
    type: TrainingType.Crossfit,
    duration: TrainingDuration.Normal,
    price: 1800,
    calories: 1200,
    description: 'Горячие предложения на Комплекс упражнений на растяжку всего тела для новичков',
    gender: Gender.AnyGender,
    video: 'video.mp4',
    rating: 5,
    coach: fakeCoach,
    isSpecial: false,
    createdAt: '2023-11-05T19:43:17.915Z',
  },
];

export const fakePopular: ITraining[] = [
  {
    id: '1',
    title: 'run, forrest, run',
    bgImage: '/assets/img/content/thumbnails/training-06.jpg',
    level: TrainingLevel.Professional,
    type: TrainingType.Beg,
    duration: TrainingDuration.Normal,
    price: 1600,
    calories: 1000,
    description: 'Узнайте правильную технику бега, развивайте выносливость и откройте для себя все секреты длительных пробежек.',
    gender: Gender.AnyGender,
    video: 'video.mp4',
    rating: 5,
    coach: fakeCoach,
    isSpecial: true,
    createdAt: '2023-11-05T19:43:17.915Z',
  },
  {
    id: '2',
    title: 'fitball',
    bgImage: '/assets/img/content/thumbnails/training-07.jpg',
    level: TrainingLevel.Professional,
    type: TrainingType.Pilates,
    duration: TrainingDuration.Normal,
    price: 1600,
    calories: 2000,
    description: 'Тренировка на фитболе; отличном тренажере для развития чувства баланса и равновесия, улучшения координации.',
    gender: Gender.AnyGender,
    video: 'video.mp4',
    rating: 5,
    coach: fakeCoach,
    isSpecial: true,
    createdAt: '2023-11-05T19:43:17.915Z',
  },
  {
    id: '3',
    title: "devil's cindy",
    bgImage: '/assets/img/content/thumbnails/training-11.jpg',
    level: TrainingLevel.Professional,
    type: TrainingType.Crossfit,
    duration: TrainingDuration.Normal,
    price: 2200,
    calories: 5000,
    description: 'Знаменитый кроссфит комплекс. Синди-универсальная тренировка для развития функциональной силы.',
    gender: Gender.AnyGender,
    video: 'video.mp4',
    rating: 5,
    coach: fakeCoach,
    isSpecial: false,
    createdAt: '2023-11-05T19:43:17.915Z',
  },
  {
    id: '4',
    title: 'full body stretch',
    bgImage: '/assets/img/content/thumbnails/training-09.jpg',
    level: TrainingLevel.Professional,
    type: TrainingType.Stretching,
    duration: TrainingDuration.Normal,
    price: 1800,
    calories: 4000,
    description: 'Комплекс упражнений на растяжку всего тела для новичков. Плавное погружение в стретчинг и умеренная нагрузка.',
    gender: Gender.AnyGender,
    video: 'video.mp4',
    rating: 5,
    coach: fakeCoach,
    isSpecial: false,
    createdAt: '2023-11-05T19:43:17.915Z',
  },
  {
    id: '5',
    title: "devil's cindy",
    bgImage: '/assets/img/content/thumbnails/training-11.jpg',
    level: TrainingLevel.Professional,
    type: TrainingType.Crossfit,
    duration: TrainingDuration.Normal,
    price: 2200,
    calories: 5000,
    description: 'Знаменитый кроссфит комплекс. Синди-универсальная тренировка для развития функциональной силы.',
    gender: Gender.AnyGender,
    video: 'video.mp4',
    rating: 5,
    coach: fakeCoach,
    isSpecial: false,
    createdAt: '2023-11-05T19:43:17.915Z',
  },
  {
    id: '6',
    title: 'full body stretch',
    bgImage: '/assets/img/content/thumbnails/training-09.jpg',
    level: TrainingLevel.Professional,
    type: TrainingType.Stretching,
    duration: TrainingDuration.Normal,
    price: 1800,
    calories: 4000,
    description: 'Комплекс упражнений на растяжку всего тела для новичков. Плавное погружение в стретчинг и умеренная нагрузка.',
    gender: Gender.AnyGender,
    video: 'video.mp4',
    rating: 5,
    coach: fakeCoach,
    isSpecial: false,
    createdAt: '2023-11-05T19:43:17.915Z',
  },
];

export const fakeOrder: ITraining[] = [
  {
    id: '1',
    title: 'Fitball',
    bgImage: '/assets/img/content/promo-1.png',
    level: TrainingLevel.Professional,
    type: TrainingType.Crossfit,
    duration: TrainingDuration.Normal,
    price: 1600,
    calories: 1200,
    description: 'Горячие предложения на тренировки на фитболе',
    gender: Gender.AnyGender,
    video: 'video.mp4',
    rating: 5,
    coach: fakeCoach,
    isSpecial: false,
    ordersCount: 2,
    ordersSumm: 3200,
    createdAt: '2023-11-05T19:43:17.915Z',
  },
  {
    id: '2',
    title: 'Fleksbend',
    bgImage: '/assets/img/content/promo-2.png',
    level: TrainingLevel.Professional,
    type: TrainingType.Crossfit,
    duration: TrainingDuration.Normal,
    price: 2400,
    calories: 1200,
    description: 'Горячие предложения наТренировки с резинкой для фитнеса',
    gender: Gender.AnyGender,
    video: 'video.mp4',
    rating: 4,
    coach: fakeCoach,
    isSpecial: false,
    ordersCount: 0,
    ordersSumm: 0,
    createdAt: '2023-11-05T19:43:17.915Z',
  },
  {
    id: '3',
    title: 'Full Body Stretch',
    bgImage: '/assets/img/content/promo-3.png',
    level: TrainingLevel.Professional,
    type: TrainingType.Crossfit,
    duration: TrainingDuration.Normal,
    price: 1800,
    calories: 1200,
    description: 'Горячие предложения на Комплекс упражнений на растяжку всего тела для новичков',
    gender: Gender.AnyGender,
    video: 'video.mp4',
    rating: 5,
    coach: fakeCoach,
    isSpecial: false,
    ordersCount: 1,
    ordersSumm: 1800,
    createdAt: '2023-11-05T19:43:17.915Z',
  },
];

export const getFakeTrainings = (count: number): ITrainingCollection => {
  const data = new Array(count).fill(null).map(() => ({
    id: faker.string.uuid(),
    title: faker.lorem.words({ min: 1, max: 2 }),
    bgImage: `/assets/img/content/thumbnails${faker.helpers.arrayElement(trainingImages)}`,
    level: faker.helpers.enumValue(TrainingLevel),
    type: faker.helpers.enumValue(TrainingType),
    duration: faker.helpers.enumValue(TrainingDuration),
    price: faker.number.int({ min: 0, max: 10000 }),
    calories: faker.number.int({ min: 1000, max: 5000 }),
    description: faker.lorem.sentence(10),
    gender: faker.helpers.enumValue(Gender),
    video: 'video.mp4',
    rating: faker.number.int({ min: 1, max: 5 }),
    coach: fakeCoach,
    isSpecial: !!faker.helpers.arrayElement([0, 1]),
    createdAt: faker.date.between({ from: '2012-01-01T00:00:00.000Z', to: '2023-01-01T00:00:00.000Z' }).toISOString(),
  }));

  return {
    data,
    page: 1,
    total: count,
  };
};

export const fakeForYouTrainings: ITrainingCollection = {
  data: forYouTrainings,
  page: 1,
  total: forYouTrainings.length,
};

export const fakeSpecialTrainings: ITrainingCollection = {
  data: fakeSpecial,
  page: 1,
  total: fakeSpecial.length,
};

export const fakePopularTraining: ITrainingCollection = {
  data: fakePopular,
  page: 1,
  total: fakePopular.length,
};

export const fakeOrderTraining: ITrainingCollection = {
  data: fakeOrder,
  page: 1,
  total: fakeOrder.length,
};
