import { CoachType, Gender, IUser, IUserCollection, Location, Role, TrainingDuration, TrainingLevel, TrainingType, UserType } from '@fit-friends/shared';

export const fakeCoach: CoachType = {
  id: 'b23b3414-e6fc-4bbf-9375-81c050ed6e3e',
  name: 'Валерия',
  email: 'valery@app.test',
  avatar: '/assets/img/content/user-photo-1.png',
  gender: Gender.Female,
  birthDay: '1985-12-04',
  bgImage: '/assets/img/content/user-coach-photo1.jpg',
  role: Role.Coach,
  bio: 'Персональный тренер и инструктор групповых программ с опытом  более 4х лет. Специализация: коррекция фигуры и осанки, снижение веса, восстановление после травм, пилатес.',
  location: Location.Sportivnaya,
  trainingLevel: TrainingLevel.Professional,
  trainingType: [TrainingType.Yoga, TrainingType.Aerobic, TrainingType.Pilates],
  certificate: [
    '/assets/img/content/certificates-and-diplomas/certificate-1.jpg',
    '/assets/img/content/certificates-and-diplomas/certificate-2.jpg',
    '/assets/img/content/certificates-and-diplomas/certificate-3.jpg',
    '/assets/img/content/certificates-and-diplomas/certificate-4.jpg',
    '/assets/img/content/certificates-and-diplomas/certificate-5.jpg',
    '/assets/img/content/certificates-and-diplomas/certificate-6.jpg',
  ],
  personalTraining: true,
  createdAt: '2019-10-10T17:37:56.678Z',
};

export const fakeUser: UserType = {
  id: 'b23b3414-e6fc-4bbf-9375-81c050ed6e3e',
  name: 'Валерия',
  email: 'valery@app.test',
  avatar: '/assets/img/content/user-photo-1.png',
  gender: Gender.Female,
  birthDay: '1985-12-04',
  bgImage: '/assets/img/content/user-card-photo1.jpg',
  role: Role.User,
  bio: 'Персональный тренер и инструктор групповых программ с опытом  более 4х лет. Специализация: коррекция фигуры и осанки, снижение веса, восстановление после травм, пилатес.',
  location: Location.Sportivnaya,
  trainingLevel: TrainingLevel.Professional,
  trainingType: [TrainingType.Yoga, TrainingType.Aerobic, TrainingType.Pilates],
  loseCalories: 3000,
  burnCalories: 4000,
  ready: true,
  createdAt: '2019-10-10T17:37:56.678Z',
};

export const testUser: IUser = {
  id: 'b23b3414-e6fc-4bbf-9375-81c050ed6e3e',
  name: 'Валерия',
  email: 'valery@app.test',
  avatar: '/assets/img/content/user-photo-1.png',
  gender: Gender.Female,
  birthDay: '1985-12-04',
  bgImage: '/assets/img/content/user-coach-photo1.jpg',
  role: Role.Coach,
  bio: 'Персональный тренер и инструктор групповых программ с опытом  более 4х лет. Специализация: коррекция фигуры и осанки, снижение веса, восстановление после травм, пилатес.',
  location: Location.Sportivnaya,
  trainingLevel: TrainingLevel.Professional,
  trainingType: [TrainingType.Yoga, TrainingType.Aerobic, TrainingType.Pilates],
  loseCalories: 3000,
  burnCalories: 4000,
  ready: true,
  certificate: [
    '/assets/img/content/certificates-and-diplomas/certificate-1.jpg',
    '/assets/img/content/certificates-and-diplomas/certificate-2.jpg',
    '/assets/img/content/certificates-and-diplomas/certificate-3.jpg',
    '/assets/img/content/certificates-and-diplomas/certificate-4.jpg',
    '/assets/img/content/certificates-and-diplomas/certificate-5.jpg',
    '/assets/img/content/certificates-and-diplomas/certificate-6.jpg',
  ],
  personalTraining: true,
  createdAt: '2019-10-10T17:37:56.678Z',
}

const fakeCompany: UserType[] = [
  {
    id: '1',
    name: 'Диана',
    email: 'diana@app.test',
    avatar: '/assets/img/content/thumbnails/user-04.jpg',
    gender: Gender.Female,
    birthDay: '1985-12-04',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.User,
    bio: 'description',
    location: Location.Sportivnaya,
    trainingLevel: TrainingLevel.Novice,
    trainingType: [TrainingType.Pilates, TrainingType.Yoga],
    createdAt: '2019-10-10T17:37:56.678Z',
  },
  {
    id: '2',
    name: 'Константин',
    email: 'diana@app.test',
    avatar: '/assets/img/content/thumbnails/user-05.jpg',
    gender: Gender.Male,
    birthDay: '1985-12-04',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.User,
    bio: 'description',
    location: Location.Pionerskaya,
    trainingLevel: TrainingLevel.Amateur,
    trainingType: [TrainingType.Power],
    createdAt: '2019-10-10T17:37:56.678Z',
  },
  {
    id: '3',
    name: 'Иван',
    email: 'diana@app.test',
    avatar: '/assets/img/content/thumbnails/user-06.jpg',
    gender: Gender.Male,
    birthDay: '1985-12-04',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.User,
    bio: 'description',
    location: Location.Udelnaya,
    trainingLevel: TrainingLevel.Novice,
    trainingType: [TrainingType.Beg],
    createdAt: '2019-10-10T17:37:56.678Z',
  },
  {
    id: '4',
    name: 'Яна',
    email: 'diana@app.test',
    avatar: '/assets/img/content/thumbnails/user-07.jpg',
    gender: Gender.Female,
    birthDay: '1985-12-04',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.User,
    bio: 'description',
    location: Location.Zvezdnaya,
    trainingLevel: TrainingLevel.Novice,
    trainingType: [TrainingType.Beg],
    createdAt: '2019-10-10T17:37:56.678Z',
  },
  {
    id: '5',
    name: 'Елена',
    email: 'diana@app.test',
    avatar: '/assets/img/content/thumbnails/user-03.jpg',
    gender: Gender.Female,
    birthDay: '1985-12-04',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.User,
    bio: 'description',
    location: Location.Sportivnaya,
    trainingLevel: TrainingLevel.Professional,
    trainingType: [TrainingType.Yoga],
    createdAt: '2019-10-10T17:37:56.678Z',
  },
  {
    id: '6',
    name: 'Александр',
    email: 'diana@app.test',
    avatar: '/assets/img/content/thumbnails/user-08.jpg',
    gender: Gender.Female,
    birthDay: '1985-12-04',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.User,
    bio: 'description',
    location: Location.Sportivnaya,
    trainingLevel: TrainingLevel.Professional,
    trainingType: [TrainingType.Boxing],
    createdAt: '2019-10-10T17:37:56.678Z',
  },
];

export const fakeUsersList: IUser[] = [
  {
    id: '1',
    name: 'Елизовета',
    email: 'elisoveta@app.test',
    avatar: '/assets/img/content/thumbnails/user-01.jpg',
    gender: Gender.Female,
    birthDay: '20.12.2012',
    role: Role.User,
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    bio: 'Привет! Я Катерина и мне 27 лет. Обожаю спорт и все, что с&nbsp;ним связанно. Регулярно хожу на&nbsp;тренировки по&nbsp;кроссфиту, также занимаюсь йогой, рястяжкой и&nbsp;пилатесом. Занимаюсь как с тренером индивидуально, так и на&nbsp;групповых занятиях. Люблю соревнования и челленджи, так что присоединяйтесь, давайте объединяться и заниматься вместе',
    location: Location.Pionerskaya,
    trainingLevel: TrainingLevel.Novice,
    trainingType: [TrainingType.Yoga, TrainingType.Crossfit],
    trainingDuration: TrainingDuration.Low,
    loseCalories: 1000,
    burnCalories: 1000,
    ready: true,
    createdAt: '20.12.2012',
  },
  {
    id: '2',
    name: 'Дарья',
    email: 'daria@app.test',
    avatar: '/assets/img/content/thumbnails/user-02.jpg',
    gender: Gender.Female,
    birthDay: '20.12.2012',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.Coach,
    bio: '',
    location: Location.Pionerskaya,
    trainingLevel: TrainingLevel.Novice,
    trainingType: [TrainingType.Yoga, TrainingType.Crossfit],
    certificate: [
      '/assets/img/content/certificates-and-diplomas/certificate-1.jpg',
      '/assets/img/content/certificates-and-diplomas/certificate-2.jpg',
    ],
    merits: '',
    personalTraining: true,
    createdAt: '20.12.2012',
  },
  {
    id: '3',
    name: 'Наталья',
    email: 'nataly@app.test',
    avatar: '/assets/img/content/thumbnails/user-03.jpg',
    gender: Gender.Female,
    birthDay: '20.12.2012',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.Coach,
    bio: '',
    location: Location.Pionerskaya,
    trainingLevel: TrainingLevel.Professional,
    trainingType: [TrainingType.Crossfit],
    certificate: [
      '/assets/img/content/certificates-and-diplomas/certificate-1.jpg',
      '/assets/img/content/certificates-and-diplomas/certificate-2.jpg',
      '/assets/img/content/certificates-and-diplomas/certificate-4.jpg',
      '/assets/img/content/certificates-and-diplomas/certificate-5.jpg',
      '/assets/img/content/certificates-and-diplomas/certificate-6.jpg',
    ],
    merits: '',
    personalTraining: true,
    createdAt: '20.12.2012',
  },
  {
    id: '4',
    name: 'Никита',
    email: 'nikita@app.test',
    avatar: '/assets/img/content/thumbnails/user-08.jpg',
    gender: Gender.Male,
    birthDay: '20.12.2012',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.Coach,
    bio: '',
    location: Location.Udelnaya,
    trainingLevel: TrainingLevel.Professional,
    trainingType: [TrainingType.Power, TrainingType.Boxing, TrainingType.Stretching],
    certificate: [
      '/assets/img/content/certificates-and-diplomas/certificate-1.jpg',
      '/assets/img/content/certificates-and-diplomas/certificate-2.jpg',
      '/assets/img/content/certificates-and-diplomas/certificate-4.jpg',
      '/assets/img/content/certificates-and-diplomas/certificate-6.jpg',
    ],
    merits: '',
    personalTraining: true,
    createdAt: '20.12.2012',
  },
  {
    id: '5',
    name: 'Татьяна',
    email: 'tatiana@app.test',
    avatar: '/assets/img/content/thumbnails/user-09.jpg',
    gender: Gender.Female,
    birthDay: '20.12.2012',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.User,
    bio: '',
    location: Location.Zvezdnaya,
    trainingLevel: TrainingLevel.Amateur,
    trainingType: [TrainingType.Power, TrainingType.Stretching],
    trainingDuration: TrainingDuration.Low,
    loseCalories: 4000,
    burnCalories: 4000,
    ready: true,
    createdAt: '20.12.2012',
  },
  {
    id: '6',
    name: 'Марк',
    email: 'mark@app.test',
    avatar: '/assets/img/content/thumbnails/user-10.jpg',
    gender: Gender.Male,
    birthDay: '20.12.2012',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.User,
    bio: '',
    location: Location.Zvezdnaya,
    trainingLevel: TrainingLevel.Amateur,
    trainingType: [TrainingType.Power, TrainingType.Stretching],
    trainingDuration: TrainingDuration.Low,
    loseCalories: 4000,
    burnCalories: 4000,
    ready: true,
    createdAt: '20.12.2012',
  },
  {
    id: '7',
    name: 'Диана',
    email: 'diana@app.test',
    avatar: '/assets/img/content/thumbnails/user-04.jpg',
    gender: Gender.Male,
    birthDay: '20.12.2012',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.Coach,
    bio: '',
    location: Location.Udelnaya,
    trainingLevel: TrainingLevel.Professional,
    trainingType: [TrainingType.Stretching],
    certificate: [
      '/assets/img/content/certificates-and-diplomas/certificate-1.jpg',
      '/assets/img/content/certificates-and-diplomas/certificate-4.jpg',
      '/assets/img/content/certificates-and-diplomas/certificate-6.jpg',
    ],
    merits: '',
    personalTraining: false,
    createdAt: '20.12.2012',
  },
  {
    id: '8',
    name: 'Станислав',
    email: 'stanislav@app.test',
    avatar: '/assets/img/content/thumbnails/user-11.jpg',
    gender: Gender.Male,
    birthDay: '20.12.2012',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.Coach,
    bio: '',
    location: Location.Sportivnaya,
    trainingLevel: TrainingLevel.Professional,
    trainingType: [TrainingType.Boxing],
    certificate: [
      '/assets/img/content/certificates-and-diplomas/certificate-1.jpg',
      '/assets/img/content/certificates-and-diplomas/certificate-4.jpg',
      '/assets/img/content/certificates-and-diplomas/certificate-6.jpg',
    ],
    merits: '',
    personalTraining: false,
    createdAt: '20.12.2012',
  },
  {
    id: '9',
    name: 'Катерина',
    email: 'katerina@app.test',
    avatar: '/assets/img/content/thumbnails/user-12.jpg',
    gender: Gender.Female,
    birthDay: '20.12.2012',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.User,
    bio: '',
    location: Location.Sportivnaya,
    trainingLevel: TrainingLevel.Professional,
    trainingType: [TrainingType.Pilates],
    trainingDuration: TrainingDuration.Normal,
    loseCalories: 2000,
    burnCalories: 2000,
    ready: false,
    createdAt: '20.12.2012',
  },
  {
    id: '10',
    name: 'Ксения',
    email: 'ksenia@app.test',
    avatar: '/assets/img/content/thumbnails/user-13.jpg',
    gender: Gender.Female,
    birthDay: '20.12.2012',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.User,
    bio: '',
    location: Location.Pionerskaya,
    trainingLevel: TrainingLevel.Novice,
    trainingType: [TrainingType.Crossfit],
    trainingDuration: TrainingDuration.Normal,
    loseCalories: 3000,
    burnCalories: 3000,
    ready: true,
    createdAt: '20.12.2012',
  },
  {
    id: '11',
    name: 'Сергей',
    email: 'sergey@app.test',
    avatar: '/assets/img/content/thumbnails/user-14.jpg',
    gender: Gender.Male,
    birthDay: '20.12.2012',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.User,
    bio: '',
    location: Location.Pionerskaya,
    trainingLevel: TrainingLevel.Novice,
    trainingType: [TrainingType.Power],
    trainingDuration: TrainingDuration.Hi,
    loseCalories: 3000,
    burnCalories: 3000,
    ready: true,
    createdAt: '20.12.2012',
  },
  {
    id: '12',
    name: 'Константин',
    email: 'konstantin@app.test',
    avatar: '/assets/img/content/thumbnails/user-05.jpg',
    gender: Gender.Male,
    birthDay: '20.12.2012',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.Coach,
    bio: '',
    location: Location.Sportivnaya,
    trainingLevel: TrainingLevel.Professional,
    trainingType: [TrainingType.Power, TrainingType.Beg, TrainingType.Boxing],
    trainingDuration: TrainingDuration.Hi,
    certificate: [
      '/assets/img/content/certificates-and-diplomas/certificate-2.jpg',
      '/assets/img/content/certificates-and-diplomas/certificate-3.jpg',
      '/assets/img/content/certificates-and-diplomas/certificate-4.jpg',
      '/assets/img/content/certificates-and-diplomas/certificate-5.jpg',
    ],
    merits: '',
    personalTraining: true,
    createdAt: '20.12.2012',
  },
  {
    id: '13',
    name: 'Владимер',
    email: 'vladimer@app.test',
    avatar: '/assets/img/content/thumbnails/user-15.jpg',
    gender: Gender.Male,
    birthDay: '20.12.2012',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.Coach,
    bio: '',
    location: Location.Zvezdnaya,
    trainingLevel: TrainingLevel.Professional,
    trainingType: [ TrainingType.Beg],
    trainingDuration: TrainingDuration.Hi,
    certificate: [
      '/assets/img/content/certificates-and-diplomas/certificate-2.jpg',
      '/assets/img/content/certificates-and-diplomas/certificate-4.jpg',
      '/assets/img/content/certificates-and-diplomas/certificate-5.jpg',
    ],
    merits: '',
    personalTraining: true,
    createdAt: '20.12.2012',
  },
  {
    id: '14',
    name: 'Алена',
    email: 'alena@app.test',
    avatar: '/assets/img/content/thumbnails/user-16.jpg',
    gender: Gender.Female,
    birthDay: '20.12.2012',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.User,
    bio: '',
    location: Location.Pionerskaya,
    trainingLevel: TrainingLevel.Novice,
    trainingType: [ TrainingType.Beg],
    trainingDuration: TrainingDuration.Low,
    loseCalories: 1500,
    burnCalories: 1500,
    ready: true,
    createdAt: '20.12.2012',
  },
  {
    id: '15',
    name: 'Леонид',
    email: 'alena@app.test',
    avatar: '/assets/img/content/thumbnails/user-17.jpg',
    gender: Gender.Male,
    birthDay: '20.12.2012',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.User,
    bio: '',
    location: Location.Udelnaya,
    trainingLevel: TrainingLevel.Amateur,
    trainingType: [ TrainingType.Pilates],
    trainingDuration: TrainingDuration.Extra,
    loseCalories: 1500,
    burnCalories: 1500,
    ready: true,
    createdAt: '20.12.2012',
  },
  {
    id: '16',
    name: 'Ева',
    email: 'eva@app.test',
    avatar: '/assets/img/content/thumbnails/user-18.jpg',
    gender: Gender.Female,
    birthDay: '20.12.2012',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.User,
    bio: '',
    location: Location.Pionerskaya,
    trainingLevel: TrainingLevel.Amateur,
    trainingType: [ TrainingType.Stretching],
    trainingDuration: TrainingDuration.Extra,
    loseCalories: 1500,
    burnCalories: 1500,
    ready: true,
    createdAt: '20.12.2012',
  },
  {
    id: '17',
    name: 'Мария',
    email: 'mary@app.test',
    avatar: '/assets/img/content/thumbnails/user-19.jpg',
    gender: Gender.Female,
    birthDay: '20.12.2012',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.Coach,
    bio: '',
    location: Location.Sportivnaya,
    trainingLevel: TrainingLevel.Professional,
    trainingType: [ TrainingType.Aerobic],
    certificate: [
      '/assets/img/content/certificates-and-diplomas/certificate-2.jpg',
      '/assets/img/content/certificates-and-diplomas/certificate-4.jpg',
      '/assets/img/content/certificates-and-diplomas/certificate-5.jpg',
    ],
    merits: '',
    personalTraining: true,
    createdAt: '20.12.2012',
  },
  {
    id: '18',
    name: 'Ирина',
    email: 'irina@app.test',
    avatar: '/assets/img/content/thumbnails/user-20.jpg',
    gender: Gender.Female,
    birthDay: '20.12.2012',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.Coach,
    bio: '',
    location: Location.Zvezdnaya,
    trainingLevel: TrainingLevel.Amateur,
    trainingType: [ TrainingType.Aerobic],
    certificate: [
      '/assets/img/content/certificates-and-diplomas/certificate-2.jpg',
    ],
    merits: '',
    personalTraining: true,
    createdAt: '20.12.2012',
  },
  {
    id: '19',
    name: 'Александра',
    email: 'alexandra@app.test',
    avatar: '/assets/img/content/thumbnails/user-21.jpg',
    gender: Gender.Female,
    birthDay: '20.12.2012',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.User,
    bio: '',
    location: Location.Pionerskaya,
    trainingLevel: TrainingLevel.Amateur,
    trainingType: [ TrainingType.Aerobic],
    trainingDuration: TrainingDuration.Extra,
    loseCalories: 1500,
    burnCalories: 1500,
    ready: true,
    createdAt: '20.12.2012',
  },
  {
    id: '20',
    name: 'Тимур',
    email: 'timur@app.test',
    avatar: '/assets/img/content/thumbnails/user-22.jpg',
    gender: Gender.Male,
    birthDay: '20.12.2012',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.User,
    bio: '',
    location: Location.Sportivnaya,
    trainingLevel: TrainingLevel.Amateur,
    trainingType: [ TrainingType.Boxing, TrainingType.Power],
    trainingDuration: TrainingDuration.Hi,
    loseCalories: 1500,
    burnCalories: 1500,
    ready: true,
    createdAt: '20.12.2012',
  },
  {
    id: '21',
    name: 'Ян',
    email: 'yn@app.test',
    avatar: '/assets/img/content/thumbnails/user-23.jpg',
    gender: Gender.Male,
    birthDay: '20.12.2012',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.Coach,
    bio: '',
    location: Location.Udelnaya,
    trainingLevel: TrainingLevel.Amateur,
    trainingType: [ TrainingType.Power],
    trainingDuration: TrainingDuration.Low,
    certificate: [
      '/assets/img/content/certificates-and-diplomas/certificate-2.jpg',
    ],
    merits: '',
    personalTraining: false,
    createdAt: '20.12.2012',
  },
  {
    id: '22',
    name: 'Яна',
    email: 'yna@app.test',
    avatar: '/assets/img/content/thumbnails/user-07.jpg',
    gender: Gender.Female,
    birthDay: '20.12.2012',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.Coach,
    bio: '',
    location: Location.Sportivnaya,
    trainingLevel: TrainingLevel.Amateur,
    trainingType: [ TrainingType.Crossfit],
    trainingDuration: TrainingDuration.Normal,
    certificate: [
      '/assets/img/content/certificates-and-diplomas/certificate-2.jpg',
    ],
    merits: '',
    personalTraining: false,
    createdAt: '20.12.2012',
  },
  {
    id: '23',
    name: 'Иван',
    email: 'ivan@app.test',
    avatar: '/assets/img/content/thumbnails/user-06.jpg',
    gender: Gender.Male,
    birthDay: '20.12.2012',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.Coach,
    bio: '',
    location: Location.Pionerskaya,
    trainingLevel: TrainingLevel.Professional,
    trainingType: [ TrainingType.Power],
    trainingDuration: TrainingDuration.Normal,
    certificate: [
      '/assets/img/content/certificates-and-diplomas/certificate-2.jpg',
    ],
    merits: '',
    personalTraining: false,
    createdAt: '20.12.2012',
  },
  {
    id: '24',
    name: 'София',
    email: 'sofy@app.test',
    avatar: '/assets/img/content/thumbnails/user-24.jpg',
    gender: Gender.Female,
    birthDay: '20.12.2012',
    bgImage: '/assets/img/content/user-card-photo1.jpg',
    role: Role.User,
    bio: '',
    location: Location.Pionerskaya,
    trainingLevel: TrainingLevel.Novice,
    trainingType: [ TrainingType.Pilates],
    trainingDuration: TrainingDuration.Normal,
    loseCalories: 1500,
    burnCalories: 1500,
    ready: false,
    createdAt: '20.12.2012',
  },
]

export const fakeCompanyUser: IUserCollection = {
  data: fakeCompany,
  page: 1,
  total: fakeCompany.length,
};

export const fakeUsers: IUserCollection = {
  data: fakeUsersList,
  page: 1,
  total: fakeUsersList.length,
}
